[package]
name = "simple-minecraft-slp-fetcher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
futures = "0.3.28"
trust-dns-resolver = "0.23.0"
varint-rs = "2.2.0"
